# netlify.toml (root-based app)

[build]
  command   = "npm ci && npm run build"
  publish   = "dist"                 # dist created by Vite
  functions = "netlify/functions"    # <repo-root>/netlify/functions

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
