# Netlify configuration (valid TOML)

[build]
  # Your code is in ./project
  base     = "project"
  command  = "npm run build"
  publish  = "dist"                # resolved from base => project/dist
  functions = "netlify/functions"  # resolved from base => project/netlify/functions

[functions]
  node_bundler = "esbuild"
  # If your functions import 'openai', keep it bundled (default). No need to externalize.
  # external_node_modules = ["openai"]  # <— usually NOT needed; comment out unless you know you need it.

[build.environment]
  NODE_VERSION = "18"

# Optional: nice API path for any future client calls
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
